services:
  mongo1:
    image: mongo:8.0
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster
    volumes:
      - mongo1_data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
    env_file:
      - .env
    command: ["mongod", "--replSet", "rs0"]

  mongo2:
    image: mongo:8.0
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster
    volumes:
      - mongo2_data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
    env_file:
      - .env
    command: ["mongod", "--replSet", "rs0"]

  mongo3:
    image: mongo:8.0
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster
    volumes:
      - mongo3_data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
    env_file:
      - .env
    command: ["mongod", "--replSet", "rs0"]

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    networks:
      - mongo-cluster
    env_file:
      - .env

networks:
  mongo-cluster:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
