echo "MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE" >.env
echo "MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME" >>.env
echo "MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD" >>.env

# Mongo Express  environment variables
echo "ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_INITDB_ROOT_USERNAME" >>.env
echo "ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_INITDB_ROOT_PASSWORD" >>.env
echo "ME_CONFIG_BASICAUTH_USERNAME=$MONGOADMIN_USERNAME" >>.env
echo "ME_CONFIG_BASICAUTH_PASSWORD=$MONGOADMIN_PASSWORD" >>.env
echo "ME_CONFIG_MONGODB_SERVER=mongo1" >>.env
