name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      contents: read # Allows reading repository content
      packages: write # Allows publishing packages to GHCR

    env:
      # Mongo cluster environment variables
      MONGO_INITDB_DATABASE: ${{ secrets.MONGO_INITDB_DATABASE }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}

      # Mongo Express  environment variables
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      ME_CONFIG_BASICAUTH_USERNAME: ${{ secrets.MONGOADMIN_USERNAME }}
      ME_CONFIG_BASICAUTH_PASSWORD: ${{ secrets.MONGOADMIN_PASSWORD }}
      ME_CONFIG_MONGODB_SERVER: mongo1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute Pre-Build Script
        run: |
          echo "MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE" >.env
          echo "MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME" >>.env
          echo "MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD" >>.env

          # Mongo Express  environment variables
          echo "ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_INITDB_ROOT_USERNAME" >>.env
          echo "ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_INITDB_ROOT_PASSWORD" >>.env
          echo "ME_CONFIG_BASICAUTH_USERNAME=$MONGOADMIN_USERNAME" >>.env
          echo "ME_CONFIG_BASICAUTH_PASSWORD=$MONGOADMIN_PASSWORD" >>.env
          echo "ME_CONFIG_MONGODB_SERVER=mongo1" >>.env

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest,
            ghcr.io/${{ github.repository }}:${{ github.run_number }}
