name: Test Private Cluster Setup

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Install Make
      run: sudo apt-get install make  # Install Make if not already installed

    - name: Create .env file
      run: |
        echo "MONGO_INITDB_DATABASE=hublotsdb" >> .env
        echo "ME_CONFIG_MONGODB_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0" >> .env
        echo "ME_CONFIG_BASICAUTH_USERNAME=admin" >> .env
        echo "ME_CONFIG_BASICAUTH_PASSWORD=admin" >> .env

    - name: Start MongoDB Cluster
      run: |
        make start  # Use Makefile to start the services and initialize the MongoDB replica set

    - name: Verify MongoDB is Running
      run: |
        docker ps | grep mongo || exit 1

    - name: Check MongoDB Replica Set
      run: |
        make check-status || exit 1

    - name: Check Mongo Express
      run: |
        # Make sure Mongo Express is running
        curl http://localhost:8081

    - name: Tear down Docker Compose
      run: |
        make down  # Use Makefile to stop and remove containers
